version: "3.8"

services:
  bit_bot:
    image: dzan/bittensor_info_bot_image
    platform: linux/amd64
    build:
      context: .
    container_name: bittensor_info_bot
    restart: unless-stopped
    volumes:
      - .:/app